Tested with emacs 29.0.50 (=emacs-version=).

To try the configuration above, clone this repository in your home folder (=~=):

#+BEGIN_SRC shell
cd
git clone git@github.com:bfonta/dot-emacs.git
#+END_SRC

and replace the contents of your =~/.emacs= file by:

#+BEGIN_SRC shell
(setq user-emacs-directory "~/dot-emacs/")
(load-file "~/dot-emacs/init.el")
#+END_SRC

During initialization you might be required to accept the download of some packages and data, depending on your system.

*Issues might happen!* Keep a backup of your files just in case, and let me know if you find some issue/bug.

** Disclaimer

I did not participate in the development of the following packages, included in this repository (at most I applied small modifications):

- =zoom/=: [[https://elpa.gnu.org/packages/yasnippet.html][frame-fns.el]], [[https://elpa.gnu.org/packages/yasnippet.html][frame-cmds.el]], [[https://elpa.gnu.org/packages/yasnippet.html][misc-fns.el]], [[https://elpa.gnu.org/packages/yasnippet.html][strings.el]] and [[https://elpa.gnu.org/packages/yasnippet.html][zoom-frm]]
- [[https://depp.brause.cc/shackle/][shackle]] (enforce appearance rules for popup windows)
- [[https://elpa.gnu.org/packages/yasnippet.htmlhttps://github.com/antonj/Highlight-Indentation-for-Emacs/blob/master/highlight-indentation.el][yasnippet]] (0.13.0)
- [[https://github.com/Bad-ptr/persp-mode.el][persp-mode]] (similar to [[https://github.com/nex3/perspective-el][perspective]])
- [[https://github.com/abo-abo/avy][avy]]
- [[https://github.com/antonj/Highlight-Indentation-for-Emacs/blob/master/highlight-indentation.el][highlight-indentation]]
- [[https://github.com/antonj/Highlight-Indentation-for-Emacs/blob/master/highlight-indentation.el][markerpen]]
- [[https://github.com/antonj/Highlight-Indentation-for-Emacs/blob/master/highlight-indentation.el][org-present]]
- [[https://github.com/casouri/vundo][vundo]] (visualize the undo tree)
- [[https://github.com/emacs-helm/helm][helm]]
- [[https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/which-func.el][which-func]]
- [[https://github.com/emacsorphanage/helm-swoop][swoop]]
- [[https://github.com/magit/magit][magit]]
- [[https://github.com/magit/with-editor][with-editor]]
- [[https://github.com/magnars/expand-region.el][expand-region]]
- [[https://github.com/magnars/multiple-cursors.el][multiple-cursors]]
- [[https://github.com/protesilaos/pulsar][pulsar]]
- [[https://github.com/takaxp/org-tree-slide][org-tree-slide]]
- [[https://www.emacswiki.org/emacs?action=browse;oldid=DeskTop;id=Desktop][desktop]]

Let me know if I ommited some package by mistake.

** GNU Emacs Installation

Emacs is [[https://github.com/emacs-mirror/emacs][mirrored in GitHub]], but the original git repository can be found [[https://savannah.gnu.org/git/?group=emacs][here]].

+ [[https://www.emacswiki.org/emacs/GccEmacs][Gcc Emacs]]: compiles ~elisp~ to native code, providing a performance improvement. Simply add the =--with-native-compilation= flag when building ~emacs~ (=./configure =--with-native-compilation ...=).

First start by installing required packages which might be required depending on the options passed to the ~./configure~ step.

#+BEGIN_SRC shell
sudo apt install build-essential ...
#+END_SRC

*** Version 29

This version notably offers =pixel-scroll-precision-mode= for the first time, which provides a smooth scrolling experience when scrolling with the mouse.

It also comes with pure GTK support, which might be good if your system supports Wayland (from my experience Wayland is still unstable on Ubuntu, possibly due to the lack of good support from Nvidia). Type =echo $XDG_SESSION_TYPE= in your terminal to know which one you are currently using.

As of 6^{th} August 2022 the latest tag points to [[https://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-28.1.91][emacs-28.1.91]]; indeed, the latest release available from the [[https://www.gnu.org/savannah-checkouts/gnu/emacs/emacs.html#Releases][official website]] is =28.1=. However, the [[https://git.savannah.gnu.org/cgit/emacs.git/tree/README][README]] file mentions "This directory tree holds version 29.0.50 of GNU Emacs". We thus can access version 29 by building it from the source code in its =master= branch.

The following steps show how to install =emacs-29=, storing it in a folder with the same name. Complete information is also available from the ~INSTALL~ file coming with the source code.

#+BEGIN_SRC shell
git clone git://git.sv.gnu.org/emacs.git emacs29
cd emacs29/
./autogen.sh
# './configure --help' displays all building options
./configure --with-native-compilation \
			--with-imagemagick \
			--with-json \
			--with-small-ja-dic \
			--with-pgtk
# You might receive an error due to missing libraries. If not, compile:
make -j8
make install
#+END_SRC

**** Sources
The following sources were consulted on 6^{th} August 2022:
+ [[https://www.gnu.org/software/emacs/manual/html_node/efaq/Installing-Emacs.html][GNU Emacs Manual: How do I install Emacs?]] (note however that no release for =emacs-29= is currently available)
+ [[https://www.emacswiki.org/emacs/GccEmacs][Gcc Emacs installation]]
+ [[https://batsov.com/articles/2021/12/19/building-emacs-from-source-with-pgtk/][Bozhidar Batsov]] article (focuses on the new ~pgtk~ support)

